In [1]:
import numpy as np
import pandas as pd

In [9]:
token_list = ["hoge", "fuga", "is", "."]

token_master_list = list(set(token_list))

sentence_list = [["hoge", "hoge", "hoge", "fuga", "."], ["fuga", "is", "hoge", "."]]

In [10]:
sentence_len_list = [0] * len(sentence_list)
for i in range(len(sentence_list)):
    sentence_len_list[i] = len(sentence_list[i])
sentence_mean_len = int(sum(sentence_len_list) / len(sentence_len_list))

In [11]:
sentence_mean_len

4

In [22]:
observed_list = [None] * len(sentence_list)
for i in range(len(sentence_list)):
    arr_list = [None] * sentence_mean_len
    for j in range(sentence_mean_len):
        try:
            token = sentence_list[i][j]
        except IndexError:
            token = None
        arr = np.zeros(len(token_master_list))
        if token is not None:
            value = 1
        else:
            value = 0
        arr[token_master_list.index(token)] = value
        arr = arr.astype(np.float64)
        arr_list[j] = arr
    observed_list[i] = arr_list
observed_arr = np.array(observed_list)

In [23]:
observed_arr.shape

(2, 4, 4)

In [24]:
observed_list

[[array([ 0.,  1.,  0.,  0.]),
  array([ 0.,  1.,  0.,  0.]),
  array([ 0.,  1.,  0.,  0.]),
  array([ 1.,  0.,  0.,  0.])],
 [array([ 1.,  0.,  0.,  0.]),
  array([ 0.,  0.,  0.,  1.]),
  array([ 0.,  1.,  0.,  0.]),
  array([ 0.,  0.,  1.,  0.])]]